version: 2.1
orbs: 
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.1
    steps:
      - checkout
      - run:
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
          working_directory: ~/project
      - restore_cache:
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          command: mvn -Puat clean package
          working_directory: ~/project
      - save_cache:
          paths:
            - ~/.m2/repository
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: ~/project/target/testms-0.1.jar
      - store_artifacts:
          path: ~/project/target/testms-0.1.jar
  deploy-to-s3:
    machine:
      image: cimg/python:3.10.4
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: ~/project/target/testms-0.1.jar
          to: 's3://lukecicleci/test/'
      - aws-s3/copy:
          arguments: '--dryrun'
          from: ~/project/target/testms-0.1.jar
          to: 's3://lukecicleci/test/'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - deploy-to-s3:
          requires:
            - build
