version: '2.1'
orbs:
  email: cinotify/email@1.2.3
jobs:
  build:
    docker:
      - image: cimg/openjdk:15.0.1
    steps:
      - checkout
      - run:
          command: find . -name 'pom.xml' | sort | xargs cat > /tmp/maven_cache_seed
          working_directory: ~/project
      - restore_cache:
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - run:
          command: mvn -Puat clean package
          working_directory: ~/project
      - save_cache:
          paths:
            - ~/.m2/repository
          key: circleci-java-maven-{{ checksum "/tmp/maven_cache_seed" }}
      - store_test_results:
          path: ~/project/target/testms-0.1.jar
      - store_artifacts:
          path: ~/project/target/testms-0.1.jar
      - persist_to_workspace:
          root: ~/project
          paths: .
  deploy-to-s3:
    docker:
      - image: 'cimg/python:3.9'
    steps:
      - checkout
      - attach_workspace:
          at: ~/project/target/testms-0.1.jar
      - run: ls
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          from: ~/project/target/testms-0.1.jar
          to: 's3://lukecicleci/test/'
      - aws-s3/copy:
          arguments: --dryrun
          from: ~/project/target/testms-0.1.jar
          to: 's3://lukecicleci/'
workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - hold:
          type: approval
      - build:
          requires:
            - hold
      - deploy-to-s3:
          requires:
            - build
